# Inspired by https://docs.docker.com/compose/django/
services:
  db:
    # NOTE: No persistance storage configured.
    # Using v14 to prevent schema permissions. See also docker-init-db.sql.
    # See: https://hub.docker.com/_/postgres/
    image: postgres:${PG_VERSION:-17}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - open-organisatie-dev

  redis:
    image: redis
    networks:
      - open-organisatie-dev 

  web:
    build: &web_build
      context: .
    image: maykinmedia/open-organisatie:latest
    environment: &web_env
      - DJANGO_SETTINGS_MODULE=openorganisatie.conf.docker
      - SECRET_KEY=${SECRET_KEY:-django-insecure-scl%uga+2ji^oa)1_*bdm^40dpn4*+gw83mw3a5=6l4(k%by&}
      - DB_NAME=openorganisatie
      - DB_USER=openorganisatie
      - DB_HOST=db
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      # Only allow all hosts for development/testing purposes!
      - ALLOWED_HOSTS=localhost,127.0.0.1,web,web.local

      # Enabling Open Telemetry requires the services in docker/docker-compose.observability.yaml
      # to be up and running.
      - OTEL_SDK_DISABLED=${OTEL_SDK_DISABLED:-true}
      - OTEL_RESOURCE_ATTRIBUTES=maykin.saas.client=maykin,maykin.saas.target=dev
      - OTEL_METRIC_EXPORT_INTERVAL=${OTEL_METRIC_EXPORT_INTERVAL:-60000}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}  # gRPC
      # otel:supersecret, escape spaces and = with percent encoding
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic b3RlbDpzdXBlcnNlY3JldA==
      - OTEL_EXPORTER_OTLP_METRICS_INSECURE=${OTEL_EXPORTER_OTLP_METRICS_INSECURE:-true}
      - _OTEL_ENABLE_CONTAINER_RESOURCE_DETECTOR=true
    ports:
      - 8000:8000
    depends_on:
      - db
    labels:
      - app=open-organisatie
      - service=api
    networks:
      - open-organisatie-dev

  celery:
    build: *web_build
    image: maykinmedia/open-organisatie:latest
    environment: *web_env
    command: /celery_worker.sh
    healthcheck:
      test: [ "CMD", "python", "/app/bin/check_celery_worker_liveness.py" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - db
      - redis
      - web
    networks:
      - open-organisatie-dev

  celery-beat:
    build: *web_build
    image: maykinmedia/open-organisatie:latest
    environment: *web_env
    command: /celery_beat.sh
    depends_on:
      - celery
    networks:
      - open-organisatie-dev

  celery-flower:
    build: *web_build
    image: maykinmedia/open-organisatie:latest
    environment: *web_env
    command: /celery_flower.sh
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    networks:
      - open-organisatie-dev

networks:
  open-organisatie-dev:
    name: open-organisatie-dev

# See: src/openorganisatie/conf/docker.py
# Optional containers below:
#  elasticsearch:
#    # NOTE: No persistance storage configured.
#    # See: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - cluster.routing.allocation.disk.threshold_enabled=false
#    ports:
#      - 9200:9200
#  redis:
#    # NOTE: No persistance storage configured.
#    # See: https://hub.docker.com/_/redis/
#    image: redis
#    ports:
#        - 6379:6379
