openapi: 3.0.3
info:
  title: Open Organisatie
  version: 0.1.0
  description: '......'
paths:
  /contactpersoon:
    get:
      operationId: contactpersoon_list
      description: Deze lijst kan gefilterd worden met query-string parameters.
      summary: Alle contactpersonen opvragen.
      parameters:
      - in: query
        name: functie
        schema:
          type: string
        description: Functie
      - name: limit
        required: false
        in: query
        description: Het aantal resultaten terug te geven per pagina.
        schema:
          type: integer
      - in: query
        name: naam
        schema:
          type: string
        description: Naam
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - Contactpersonen
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedContactpersoonList'
          description: ''
  /contactpersoon/{uuid}:
    get:
      operationId: contactpersoon_retrieve
      description: Een specifieke contactpersoon opvragen via UUID.
      summary: Een specifieke contactpersoon opvragen.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
          description: Unieke resource identifier (UUID4)
        required: true
      tags:
      - Contactpersonen
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contactpersoon'
          description: ''
  /medewerkers:
    get:
      operationId: medewerkers_list
      description: Deze lijst kan gefilterd wordt met query-string parameters.
      summary: Alle medewerkers opvragen.
      parameters:
      - in: query
        name: actief
        schema:
          type: boolean
        description: Actief
      - in: query
        name: datumToegevoegd
        schema:
          type: string
          format: date
        description: Datum toegevoegd
      - in: query
        name: datumUitDienst
        schema:
          type: string
          format: date
        description: Datum uit dienst
      - in: query
        name: functie
        schema:
          type: string
        description: Functie
      - in: query
        name: geslachtsaanduiding
        schema:
          type: boolean
        description: Geslachtsaanduiding
      - name: limit
        required: false
        in: query
        description: Het aantal resultaten terug te geven per pagina.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: teams
        schema:
          type: array
          items:
            type: string
            nullable: true
        description: Teams
        explode: true
        style: form
      tags:
      - Medewerkers
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMedewerkerList'
          description: ''
  /medewerkers/{oid}:
    get:
      operationId: medewerkers_retrieve
      description: Een specifieke medewerker opvragen.
      summary: Een specifieke medewerker opvragen.
      parameters:
      - in: path
        name: oid
        schema:
          type: string
          format: uuid
          title: Azure Object ID
          description: Unieke Azure Active Directory Object ID van de medewerker.
        required: true
      tags:
      - Medewerkers
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medewerker'
          description: ''
  /organisatorische-eenheid:
    get:
      operationId: organisatorische_eenheid_list
      description: Deze lijst kan gefilterd worden met query-string parameters.
      summary: Alle organisatorische eenheden opvragen.
      parameters:
      - in: query
        name: beschrijving
        schema:
          type: string
        description: Beschrijving
      - in: query
        name: einddatum
        schema:
          type: string
          format: date
        description: Einddatum
      - in: query
        name: emailadres
        schema:
          type: string
        description: E-mailadres
      - in: query
        name: identificatie
        schema:
          type: string
        description: Identificatie
      - name: limit
        required: false
        in: query
        description: Het aantal resultaten terug te geven per pagina.
        schema:
          type: integer
      - in: query
        name: naam
        schema:
          type: string
        description: Naam
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: telefoonnummer
        schema:
          type: string
        description: Telefoonnummer
      - in: query
        name: typeOrganisatie
        schema:
          type: string
        description: Type organisatie
      - in: query
        name: verkorteNaam
        schema:
          type: string
        description: Verkorte naam
      tags:
      - Organisatorische Eenheden
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganisatorischeEenheidList'
          description: ''
  /organisatorische-eenheid/{uuid}:
    get:
      operationId: organisatorische_eenheid_retrieve
      description: Een specifieke organisatorische eenheid opvragen aan de hand van
        de identificatie.
      summary: Een specifieke organisatorische eenheid opvragen.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
          description: Unieke resource identifier (UUID4)
        required: true
      tags:
      - Organisatorische Eenheden
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisatorischeEenheid'
          description: ''
  /teams:
    get:
      operationId: teams_list
      description: Deze lijst kan gefilterd wordt met query-string parameters.
      summary: Alle teams opvragen.
      parameters:
      - in: query
        name: actief
        schema:
          type: boolean
        description: Actief
      - name: limit
        required: false
        in: query
        description: Het aantal resultaten terug te geven per pagina.
        schema:
          type: integer
      - in: query
        name: naam
        schema:
          type: string
        description: Naam
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - Team
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTeamList'
          description: ''
  /teams/{oid}:
    get:
      operationId: teams_retrieve
      description: Een specifieke medewerker opvragen.
      summary: Een specifieke team opvragen.
      parameters:
      - in: path
        name: oid
        schema:
          type: string
          description: A string that is an identifier for the resource as defined
            by the provisioning client.
        required: true
      tags:
      - Team
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: ''
  /vestiging:
    get:
      operationId: vestiging_list
      description: Deze lijst kan gefilterd worden met query-string parameters.
      summary: Alle vestigingen opvragen.
      parameters:
      - in: query
        name: adres
        schema:
          type: string
        description: Adres
      - in: query
        name: correspondentieadres
        schema:
          type: string
        description: Correspondentieadres
      - in: query
        name: korteNaam
        schema:
          type: string
        description: Korte naam
      - in: query
        name: landcode
        schema:
          type: string
        description: Landcode
      - name: limit
        required: false
        in: query
        description: Het aantal resultaten terug te geven per pagina.
        schema:
          type: integer
      - in: query
        name: naam
        schema:
          type: string
        description: Naam
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: organisatorischeEenheid
        schema:
          type: string
          format: uuid
        description: Organisatorische eenheid (UUID)
      - in: query
        name: postadres
        schema:
          type: string
        description: Postadres
      - in: query
        name: telefoonnummer
        schema:
          type: string
        description: Telefoonnummer
      - in: query
        name: vestigingsnummer
        schema:
          type: string
        description: Vestigingsnummer
      tags:
      - Vestigingen
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedVestigingList'
          description: ''
  /vestiging/{uuid}:
    get:
      operationId: vestiging_retrieve
      description: Een specifieke vestiging opvragen aan de hand van het vestigingsnummer.
      summary: Een specifieke vestiging opvragen.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
          description: Unieke resource identifier (UUID4)
        required: true
      tags:
      - Vestigingen
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vestiging'
          description: ''
components:
  schemas:
    Contactpersoon:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        naam:
          type: string
        functie:
          type: string
        emailadres:
          type: string
          format: email
        telefoonnummer:
          type: string
      required:
      - naam
      - uuid
    Medewerker:
      type: object
      properties:
        oid:
          type: string
          format: uuid
          readOnly: true
        voornaam:
          type: string
        achternaam:
          type: string
        emailadres:
          type: string
          format: email
        functie:
          type: string
        telefoonnummer:
          type: string
        geslachtsaanduiding:
          type: boolean
        datum_uit_dienst:
          type: string
          format: date
          nullable: true
        actief:
          type: boolean
        teams:
          type: array
          items:
            $ref: '#/components/schemas/Team'
          readOnly: true
        datum_toegevoegd:
          type: string
          format: date-time
          readOnly: true
        laatst_gewijzigd:
          type: string
          format: date-time
          readOnly: true
      required:
      - achternaam
      - actief
      - datum_toegevoegd
      - emailadres
      - geslachtsaanduiding
      - laatst_gewijzigd
      - oid
      - teams
      - voornaam
    OrganisatorischeEenheid:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        identificatie:
          type: string
        naam:
          type: string
        type_organisatie:
          type: string
        verkorte_naam:
          type: string
        beschrijving:
          type: string
        emailadres:
          type: string
          format: email
        telefoonnummer:
          type: string
        einddatum:
          type: string
          format: date
          nullable: true
      required:
      - identificatie
      - naam
      - type_organisatie
      - uuid
    PaginatedContactpersoonList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Contactpersoon'
    PaginatedMedewerkerList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Medewerker'
    PaginatedOrganisatorischeEenheidList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/OrganisatorischeEenheid'
    PaginatedTeamList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Team'
    PaginatedVestigingList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Vestiging'
    Team:
      type: object
      properties:
        oid:
          type: string
          format: uuid
          readOnly: true
        naam:
          type: string
        beschrijving:
          type: string
        actief:
          type: boolean
      required:
      - actief
      - beschrijving
      - naam
      - oid
    Vestiging:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        vestigingsnummer:
          type: string
        naam:
          type: string
        korte_naam:
          type: string
        adres:
          type: string
        correspondentieadres:
          type: string
        postadres:
          type: string
        telefoonnummer:
          type: string
        landcode:
          type: string
        organisatorische_eenheid:
          allOf:
          - $ref: '#/components/schemas/OrganisatorischeEenheid'
          readOnly: true
      required:
      - naam
      - organisatorische_eenheid
      - uuid
      - vestigingsnummer
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
servers:
- url: /medewerksers/api/v0
