name: OAS

on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  oas:
    name: Checks

    uses: maykinmedia/open-api-workflows/.github/workflows/oas.yml@v5
    with:
      python-version: "3.12"
      django-settings-module: openorganisatie.conf.ci
      oas-generate-command: bin/generate_api_schema.sh
      schema-path: src/openorganisatie/scim/scim-openapi.yaml
      oas-artifact-name: scim-api-oas
      node-version-file: ".nvmrc"
      spectral-version: "^6.15.0"
      openapi-to-postman-version: "^5.0.0"
      postman-artifact-name: scim-api-postman-collection
      openapi-generator-version: "^2.20.0"
      spectral-ruleset: https://static.developer.overheid.nl/adr/2.1/ruleset.yaml
